server:
  port: 8088
  ssl:
    enabled: false
mybatis:
  type-aliases-packages: cn.jason.model

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  datasource2:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    cn:
      jason:
        mapper: DEBUG
rest:
  upload:
    dir: upload-dir
